### ISSUE TITLE
IP is very readable

### ISSUE THREAD

**Issue by TudbuT** [ChillerDragon/zillybot-mc#8]
Scale it down 66% and it's easy to read, to fix that, put a black bar on it, otherwise it might ruin the challenge.

**Comment by ChillerDragon** [comment]
I messed with the image which should make it much harder if not misleading. The old image is still in the git history. But I would argue that this repo is only known to insiders anyways. If it gets found by others and they un blur the image from the git history they deserve it imo or have enough fun.
